default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"
  permission: ["admin"]

se-connecter:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

login:
  controller: "Security"
  action: "login"

confirm-user-inscription:
  controller: "Security"
  action: "confirmUserEmail"

deconnexion:
  controller: "Security"
  action: "logout"

dashboard:
  controller: "UserController"
  action: "index"
  permission: ["admin", "guest", "suscriber"]

profil:
  controller: "UserController"
  action: "index"
  permission: ["admin", "guest", "suscriber"]
