default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"
  permission: ["admin"]

se-connecter:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

login:
  controller: "Security"
  action: "login"

confirm-user-inscription:
  controller: "Security"
  action: "confirmUserEmail"

deconnexion:
  controller: "Security"
  action: "logout"

dashboard:
  controller: "Admin"
  action: "getUsers"
  permission: ["admin"]

dashboard-pages:
  controller: "Admin"
  action: "getPages"
  permission: ["admin"]

dashboard-reportings:
  controller: "Admin"
  action: "getReportings"
  permission: ["admin"]

switch-page-status:
  controller: "Admin"
  action: "switchPageStatus"
  permission: ["admin"]

hard-delete-user:
  controller: "Admin"
  action: "hardDeleteUser"
  permission: ["admin"]

soft-delete-user:
  controller: "Admin"
  action: "softDeleteUser"

update-user:
  controller: "Admin"
  action: "updateUser"
  permission: ["admin"]

profil:
  controller: "UserController"
  action: "index"
  permission: ["admin", "guest", "suscriber"]

wireframe1:
  controller: "DesignTestController"
  action: "displayWireframe1"

wireframe2:
  controller: "DesignTestController"
  action: "displayWireframe2"

wireframe3:
  controller: "DesignTestController"
  action: "displayWireframe3"

create-page:
  controller: "PageController"
  action: "create"
  permission: ["admin"]

update-page:
  controller: "PageController"
  action: "update"
  permission: ["admin"]

validate-comment:
  controller: "Admin"
  action: "validateComment"
  permission: ["admin"]

block-comment:
  controller: "Admin"
  action: "blockComment"
  permission: ["admin"]

# route for deployement CMS

deploy:
  controller: "Deploy"
  action: "deployDb"

deploy/user:
  controller: "Deploy"
  action: "deployUser"
