default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"
  permission: ["admin"]

se-connecter:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

login:
  controller: "Security"
  action: "login"

confirm-user-inscription:
  controller: "Security"
  action: "confirmUserEmail"

deconnexion:
  controller: "Security"
  action: "logout"

dashboard:
  controller: "Admin"
  action: "getUsers"

hard-delete-user:
  controller: "Admin"
  action: "hardDeleteUser"
  permission: ["admin"]

soft-delete-user:
  controller: "Admin"
  action: "softDeleteUser"

update-user:
  controller: "Admin"
  action: "updateUser"
  permission: ["admin"]

profil:
  controller: "UserController"
  action: "index"
  permission: ["admin", "guest", "suscriber"]

design:
  controller: "DesignTestController"
  action: "displayWireframe1"
